name: Build and deploy JAR app to Azure Web App - sparkjava

on:
  push:
    branches:
      - master

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false   
    goals: 'package'
    
    - task: CopyFiles@2
  inputs:
    contents: '**/*.war'
    targetFolder: '$(build.artifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'war'
    pathToPublish: '$(build.artifactStagingDirectory)'
